### ISSUE TITLE
FYI/CRASH REPORT

### ISSUE THREAD

**Issue by Nexusdog** [Orange1861/Improved-Villagers#21]
Occurred trying to exit game in latest test. 

---- Minecraft Crash Report ----

WARNING: coremods are present:
  IvToolkit (IvToolkit-1.3.3-1.12.jar)
Contact their authors BEFORE contacting forge

// Hi. I'm Minecraft, and I'm a crashaholic.

Time: 8/17/17 11:51 PM
Description: Exception ticking world

java.lang.OutOfMemoryError: Requested array size exceeds VM limit
	at java.util.Arrays.copyOf(Arrays.java:3332)
	at java.lang.AbstractStringBuilder.expandCapacity(AbstractStringBuilder.java:137)
	at java.lang.AbstractStringBuilder.ensureCapacityInternal(AbstractStringBuilder.java:121)
	at java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:421)
	at java.lang.StringBuilder.append(StringBuilder.java:136)
	at ivorius.reccomplex.utils.tokenizer.TokenReplacer.evaluate(TokenReplacer.java:56)
	at ivorius.reccomplex.random.Poem.evaluate(Poem.java:99)
	at ivorius.reccomplex.random.Poem.randomPoem(Poem.java:50)
	at ivorius.reccomplex.random.item.Book.poem(Book.java:52)
	at ivorius.reccomplex.random.item.Book.any(Book.java:35)
	at ivorius.reccomplex.item.ItemBookGenerator.generateInInventory(ItemBookGenerator.java:42)
	at ivorius.reccomplex.world.storage.loot.InventoryGenerationHandler.generateAllTags(InventoryGenerationHandler.java:59)
	at ivorius.reccomplex.world.storage.loot.InventoryGenerationHandler.generateAllTags(InventoryGenerationHandler.java:72)
	at ivorius.reccomplex.world.gen.feature.structure.generic.GenericStructure.generateTileEntityContents(GenericStructure.java:162)
	at ivorius.reccomplex.world.gen.feature.structure.generic.GenericStructure.setBlock(GenericStructure.java:147)
	at ivorius.reccomplex.world.gen.feature.structure.generic.GenericStructure.generate(GenericStructure.java:249)
	at ivorius.reccomplex.world.gen.feature.structure.generic.GenericStructure.generate(GenericStructure.java:71)
	at ivorius.reccomplex.world.gen.feature.StructureGenerator.generate(StructureGenerator.java:156)
	at ivorius.reccomplex.world.gen.feature.structure.generic.maze.WorldGenMaze.generate(WorldGenMaze.java:59)
	at ivorius.reccomplex.world.gen.script.WorldScriptMazeGenerator.generate(WorldScriptMazeGenerator.java:102)
	at ivorius.reccomplex.world.gen.script.WorldScriptMazeGenerator.generate(WorldScriptMazeGenerator.java:52)
	at ivorius.reccomplex.world.gen.script.WorldScriptMulti.generate(WorldScriptMulti.java:64)
	at ivorius.reccomplex.block.TileEntityBlockScript.generate(TileEntityBlockScript.java:71)
	at ivorius.reccomplex.block.TileEntityBlockScript.generate(TileEntityBlockScript.java:25)
	at ivorius.reccomplex.world.gen.feature.structure.generic.GenericStructure.lambda$generate$72(GenericStructure.java:296)
	at ivorius.reccomplex.world.gen.feature.structure.generic.GenericStructure$$Lambda$374/1026057946.accept(Unknown Source)
	at java.util.HashMap$EntrySet.forEach(HashMap.java:1035)
	at ivorius.reccomplex.world.gen.feature.structure.generic.GenericStructure.generate(GenericStructure.java:291)
	at ivorius.reccomplex.world.gen.feature.structure.generic.GenericStructure.generate(GenericStructure.java:71)
	at ivorius.reccomplex.world.gen.feature.StructureGenerator.generate(StructureGenerator.java:206)
	at ivorius.reccomplex.world.gen.feature.WorldGenStructures.planStructureInChunk(WorldGenStructures.java:120)
	at ivorius.reccomplex.world.gen.feature.WorldGenStructures.lambda$planStructuresInChunk$845(WorldGenStructures.java:77)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at java.util.Arrays.copyOf(Arrays.java:3332)
	at java.lang.AbstractStringBuilder.expandCapacity(AbstractStringBuilder.java:137)
	at java.lang.AbstractStringBuilder.ensureCapacityInternal(AbstractStringBuilder.java:121)
	at java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:421)
	at java.lang.StringBuilder.append(StringBuilder.java:136)
	at ivorius.reccomplex.utils.tokenizer.TokenReplacer.evaluate(TokenReplacer.java:56)
	at ivorius.reccomplex.random.Poem.evaluate(Poem.java:99)
	at ivorius.reccomplex.random.Poem.randomPoem(Poem.java:50)
	at ivorius.reccomplex.random.item.Book.poem(Book.java:52)
	at ivorius.reccomplex.random.item.Book.any(Book.java:35)
	at ivorius.reccomplex.item.ItemBookGenerator.generateInInventory(ItemBookGenerator.java:42)
	at ivorius.reccomplex.world.storage.loot.InventoryGenerationHandler.generateAllTags(InventoryGenerationHandler.java:59)
	at ivorius.reccomplex.world.storage.loot.InventoryGenerationHandler.generateAllTags(InventoryGenerationHandler.java:72)
	at ivorius.reccomplex.world.gen.feature.structure.generic.GenericStructure.generateTileEntityContents(GenericStructure.java:162)
	at ivorius.reccomplex.world.gen.feature.structure.generic.GenericStructure.setBlock(GenericStructure.java:147)
	at ivorius.reccomplex.world.gen.feature.structure.generic.GenericStructure.generate(GenericStructure.java:249)
	at ivorius.reccomplex.world.gen.feature.structure.generic.GenericStructure.generate(GenericStructure.java:71)
	at ivorius.reccomplex.world.gen.feature.StructureGenerator.generate(StructureGenerator.java:156)
	at ivorius.reccomplex.world.gen.feature.structure.generic.maze.WorldGenMaze.generate(WorldGenMaze.java:59)
	at ivorius.reccomplex.world.gen.script.WorldScriptMazeGenerator.generate(WorldScriptMazeGenerator.java:102)
	at ivorius.reccomplex.world.gen.script.WorldScriptMazeGenerator.generate(WorldScriptMazeGenerator.java:52)
	at ivorius.reccomplex.world.gen.script.WorldScriptMulti.generate(WorldScriptMulti.java:64)
	at ivorius.reccomplex.block.TileEntityBlockScript.generate(TileEntityBlockScript.java:71)
	at ivorius.reccomplex.block.TileEntityBlockScript.generate(TileEntityBlockScript.java:25)
	at ivorius.reccomplex.world.gen.feature.structure.generic.GenericStructure.lambda$generate$72(GenericStructure.java:296)
	at ivorius.reccomplex.world.gen.feature.structure.generic.GenericStructure$$Lambda$374/1026057946.accept(Unknown Source)
	at java.util.HashMap$EntrySet.forEach(HashMap.java:1035)

-- Affected level --
Details:
	Level name: IV #8
	All players: 1 total; [EntityPlayerMP['nexusdog'/7515, l='IV #8', x=33.16, y=145.00, z=110.05]]
	Chunk stats: ServerChunkCache: 1685 Drop: 0
	Level seed: -7220929841549340239
	Level generator: ID 06 - BIOMESOP, ver 0. Features enabled: true
	Level generator options: 
	Level spawn location: World: (0,64,248), Chunk: (at 0,4,8 in 0,15; contains blocks 0,0,240 to 15,255,255), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 1506 game time, 1506 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 152407 (now: false), thunder time: 168826 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:755)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:665)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:523)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.12
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 3169239080 bytes (3022 MB) / 6690009088 bytes (6380 MB) up to 12831227904 bytes (12236 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx12G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn512M
	IntCache: cache: 0, tcache: 0, allocated: 4, tallocated: 105
	FML: MCP 9.40 Powered by Forge 14.21.1.2443 17 mods loaded, 17 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAAAAAAA	minecraft{1.12} [Minecraft] (minecraft.jar) 
	UCHIJAAAAAAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAAAAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.12-14.21.1.2443.jar) 
	UCHIJAAAAAAAAA	forge{14.21.1.2443} [Minecraft Forge] (forge-1.12-14.21.1.2443.jar) 
	UCHIJAAAAAAAAA	ivtoolkit{1.3.3-1.12} [IvToolkit] (minecraft.jar) 
	UCHIJAAAAAAAAA	biomesoplenty{7.0.0.2291} [Biomes O' Plenty] (BiomesOPlenty-1.12-7.0.0.2291-universal.jar) 
	UCHIJAAAAAAAAA	cs{3.0.0} [Configurable Villager to Door Ratio] (cs-3.0.0.jar) 
	UCHIJAAAAAAAAA	cyclopscore{0.10.12} [Cyclops Core] (CyclopsCore-1.12-0.10.12.jar) 
	UCHIJAAAAAAAAA	everlastingabilities{1.3.2} [EverlastingAbilities] (EverlastingAbilities-1.12-1.3.2.jar) 
	UCHIJAAAAAAAAA	mantle{1.12-1.3.1.18} [Mantle] (Mantle-1.12-1.3.1.18.jar) 
	UCHIJAAAAAAAAA	natura{1.12-4.3.0.16} [Natura] (Natura-1.12-4.3.0.16.jar) 
	UCHIJAAAAAAAAA	forestry{5.5.0.169} [Forestry] (forestry_1.12-5.5.0.169.jar) 
	UCHIJAAAAAAAAA	iv{3.0.0} [Improved Villagers] (Improved Villagers-3.0.0.jar) 
	UCHIJAAAAAAAAA	journeymap{1.12-5.4.9} [JourneyMap] (journeymap-1.12-5.4.9.jar) 
	UCHIJAAAAAAAAA	levelup2{${version}} [Level Up! Reloaded] (Level Up! 2-1.1.4-1.12.jar) 
	UCHIJAAAAAAAAA	reccomplex{1.4.5} [Recurrent Complex] (RecurrentComplex-1.4.5.jar) 
	UCHIJAAAAAAAAA	ruins{16.7} [Ruins Mod] (Ruins-1.12.jar) 
	Loaded coremods (and transformers): 
IvToolkit (IvToolkit-1.3.3-1.12.jar)
  
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Pulsar/natura loaded Pulses: 
		- NaturaCommons (Enabled/Forced)
		- NaturaOverworld (Enabled/Not Forced)
		- NaturaNether (Enabled/Not Forced)
		- NaturaDecorative (Enabled/Not Forced)
		- NaturaTools (Enabled/Not Forced)
		- NaturaEntities (Enabled/Not Forced)
		- NaturaOredict (Enabled/Forced)
		- NaturaWorld (Enabled/Not Forced)

	Profiler Position: N/A (disabled)
	Player Count: 1 / 8; [EntityPlayerMP['nexusdog'/7515, l='IV #8', x=33.16, y=145.00, z=110.05]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'

**Comment by Orange1861** [comment]
Oops, forgot to post a comment here:

This looks like an issue with recurrent complex.
